version: '3.2'

volumes:
    database_data:
        driver: local
    phpsocket:

services:
    mysql:
        image: mysql:5.7
        container_name: st_mysql
        ports:
            - ${DATABASE_HOST_PORT}:3306
        volumes:
            - ./docker/mysql/data/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}

    php:
        build:
            context: docker/dockerfile/phpfpm
        container_name: st_phpfpm
        volumes:
            - ./:/var/www/html/
        links:
            - mysql
            - selenium
        user: www-data

    httpd:
        container_name: st_httpd
        image: docker.bayard.io/transverse/packages/docker/alpine/httpd/2.4:latest
        ports:
            - ${WWW_HOST_PORT}:80
        environment:
            VIRTUAL_HOST: bayardtest.local
            DOCUMENT_ROOT: /var/www/html/web/
            PHP_BACKEND_HOST: php:9000
        volumes:
            - .:/var/www/html/
        links:
            - php

    selenium:
        image: selenium/standalone-chrome-debug
        container_name: st_selenium
        ports:
            - 5900
        external_links:
            - httpd:bayardtest.local
