bayard_test_user:
    resource: "@BayardTestUserBundle/Controller/"
    type:     annotation
    prefix:   /

bayard_test_platform:
    resource: '@BayardTestPlatformBundle/Controller/'
    type: annotation

# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation
login:
    path: /login
    defaults:
        _controller: BayardTestUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout