services:
#    bayard_test_user.example:
#        class: BayardTest\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

     
     BayardTest\UserBundle\DataFixtures\ORM\LoadUser:
         tags: ['doctrine.fixture.orm']
